---
abstract: 'A hash-based object implementation with key alias and'
author:
  - 'Kentaro Kuribayashi, <kentarok@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Compact
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Scalar::Util: 0
  perl: 5.8.1
resources:
  bugtracker: https://github.com/kentaro/perl-hash-compact/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kentaro/perl-hash-compact.git
version: 0.04
